start: compile run

compile: 
	javac life_beings/*.java && javac exceptions/*.java && javac main/*.java 

run:
	java main.Main 

clean:
	rm life_beings/*.class && rm exceptions/*.class && rm main/*.class

